default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: off_lead_development

test:
  <<: *default
  database: off_lead_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>
  socket: /var/lib/mysql/mysql.sock
