default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 
  host: db
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: off_lead_development

test:
  <<: *default
  database: off_lead_test

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: <%= ENV['DB_NAME'] %>
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock
